### ISSUE TITLE
timing scripts should detect failure of 'git checkout'

### ISSUE THREAD

**Issue by mikeshulman** [JasonGross/coq-scripts#1]
If I accidentally set `PREV_COMMIT` to a nonexistent git identifier (which I just managed to do -- not sure exactly how, maybe a cut and paste mistake), `git checkout` will exit with an error, but the timing scripts don't notice and proceed to compile the same branch twice.

**Comment by JasonGross** [comment]
My first guess: you pasted a sha1 from github without running `git remote update`, so, e.g., you were telling it to look for a version of `master` it didn't know about yet.  Anyway, it should be fixed now.

**Comment by mikeshulman** [comment]
Thanks!  I was trying to paste a sha1 from gitk, actually, but it seems that I managed to paste it twice without noticing.
