### ISSUE TITLE
Use of VectorDef in compat files breaks extraction

### ISSUE THREAD

**Issue by cpitclaudel** [JasonGross/coq-scripts#4]
Hi there,

In 8.7.2 (and probably 8.8?), Coq gets confused when a project uses both VectorDef and Vector.  Concretely, the generated Ocaml code looks like this:

```

type 'a t1 =
| Nil
| Cons of 'a * int * 'a t1

type 'a t2 =
| Nil0
| Cons0 of 'a * int * 'a t2
```

And OCaml complains loudly about this issue:

```
This variant expression is expected to have type consSig t2
       The constructor Nil does not belong to type t2
Hint: Did you mean Nil0?
```

It goes away if I locally edit my copy of coq-scripts in Fiat's etc/ directory to replace all instances of VectorDef by Vector.  Should that change be in coq-scripts? Will it break anything?

Thanks!

**Comment by JasonGross** [comment]
Sure, feel free to submit a PR that does this.  I'm not aware of any project that uses the compat files other than fiat.
