### ISSUE TITLE
strictify-coqdep should not call python2

### ISSUE THREAD

**Issue by cpitclaudel** [JasonGross/coq-scripts#6]
Python2 is EOL at this point, so we should move the script to python3

**Comment by JasonGross** [comment]
I will gladly accept pull requests that do this, otherwise it'll be a bit before I get around to doing it myself

**Comment by cpitclaudel** [comment]
There's no hurry :) Thanks a lot!

**Comment by JasonGross** [comment]
Fixed now (I got around to it sooner than I thought I would)

**Comment by cpitclaudel** [comment]
Thanks!
